name: cd
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

dependencies:
  args: ^2.3.0
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  logger: ^2.0.2+1
  shelf: ^1.4.0
  shelf_hotreload: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.6
  http: ^0.13.0
  lints: ^2.0.0
  shelf_router_generator: ^1.1.0
  test: ^1.21.0
  json_annotation: ^4.8.1

